# Database Connection Settings
# Use your Mac username if 'postgres' fails
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=swaralikestikar
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Important for local debugging
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect